In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
import polyphase
import numpy as np
import matplotlib.pyplot as plt
import pdb

In [18]:
M = [406.193,5.99,1]
chi = [0.435,0.77,1.00]
f = lambda x : polyphase.flory_huggins(x, M, chi)
engine = polyphase.PHASE(f,100,3)
engine.compute(lower_hull_method = 'point_at_infinity', correction=3)

Computation took 1.51s


In [19]:
boundary_points = np.asarray([engine.is_boundary_point(x) for x in engine.grid.T])
no_boundary_grid = np.where(~boundary_points)[0]
point = engine.grid[:,np.random.choice(no_boundary_grid)]
print(point)
engine(point)

[0.02020203 0.82828283 0.15151516]


(array([7.32251375e-15, 9.64267870e-01, 5.67571524e-14]),
 array([[7.9797980e-01, 5.0505060e-02, 1.5151516e-01],
        [1.0000000e-08, 8.5858586e-01, 1.4141415e-01],
        [1.0000000e-08, 8.4848485e-01, 1.5151516e-01]]),
 2)

In [42]:
# Perform phase splitting test
PHASE_ID = 3
phase_simplices_ids = np.where(np.asarray(engine.num_comps)==PHASE_ID)[0]
failed = []
criteria = engine.df.T['label']==PHASE_ID
lengths = []
for simplex_id in phase_simplices_ids:
    test = polyphase.TestPhaseSplits(engine,phase=PHASE_ID,simplex_id=simplex_id, threshold=0.05)
    out = test.check_centroid()

RuntimeError: The chosen simplex with vertices [[6.1616162e-01 1.0000000e-08 3.8383839e-01]
 [4.9494950e-01 1.0000000e-08 5.0505051e-01]
 [1.0000000e-08 1.0000000e-08 1.0000000e+00]] is flat.The tests cannot be performed.